language: node_js

install:
  - npm install -g codecov

node_js:
  - 11
  - 10
  - 9
  - 8
  - 7
  - 6

script:
  - yarn test

jobs:
  include:
    - stage: coverage
      node_js: "6"
      script:
        - yarn coverage
        - codecov
